server:
  port: 7573

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth:7771
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: http://product:7773
          predicates:
            - Path=/product/**

    nacos:
      discovery:
        server-addr: nacos:8848
        # 单机新 Nacos 默认 public namespace

gateway:
  whitelist:
    - /auth/**
